# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Gradle@2
  displayName: 'Gradle $(gradleWrapperFile)'
  inputs:
    workingDirectory: '$(Build.SourcesDirectory)'
    gradleWrapperFile: '$(Build.SourcesDirectory)/src/Seeder/gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Unit Test'
    tasks: 'build'
    sonarQubeRunAnalysis: false

- task: CopyFiles@2
  displayName: 'Copy File to: $(TargetFolder)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
     **/*.war
     **/*jar-with-dependencies.jar
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true
